<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="InvalidNegativeNumberException.fs" />
        <Compile Include="Calculator.fs" />

    </ItemGroup>

</Project>
